# Generated by Django 3.2 on 2024-04-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_remove_term_inverse_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentterms',
            name='inverse_frequency',
        ),
    ]
