# Generated by Django 3.2 on 2024-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_remove_documentterms_inverse_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='inverse_frequency',
            field=models.FloatField(null=True),
        ),
    ]
